/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import com.mycompany.crudcentroeducativo.Entidades.Alumno;
import com.mycompany.crudcentroeducativo.Entidades.Autorizaciones;
import com.mycompany.crudcentroeducativo.Entidades.Autorizado;
import com.mycompany.crudcentroeducativo.controladorDAO.AlumnoDao;
import com.mycompany.crudcentroeducativo.controladorDAO.AlumnoDaoImp;
import com.mycompany.crudcentroeducativo.controladorDAO.AutorizacionesDaoImp;
import com.mycompany.crudcentroeducativo.controladorDAO.AutorizadoDaoImp;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alejandrobalangutierrez
 */
public class frmAutorizaciones extends javax.swing.JFrame {

    private Alumno miAlumnoInterno;
    private Autorizado miAutorizadoInterno;

    /**
     * Creates new form frmAutorizaciones
     */
    public frmAutorizaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDniAlumno = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        lblNombres = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoAlumno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtDniAutorizado = new javax.swing.JTextField();
        btnBuscarAutorizado = new javax.swing.JButton();
        lblNombres1 = new javax.swing.JLabel();
        txtNombreAutorizado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoAutorizado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddAutorizacion = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AUTORIZACIONES");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setText("DNI del Alumno");

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        lblNombres.setText("Nombre");

        txtNombreAlumno.setEditable(false);

        jLabel6.setText("Apellido 1");

        txtApellidoAlumno.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblNombres)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDniAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtNombreAlumno)
                    .addComponent(txtApellidoAlumno))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAlumno)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        btnBuscarAutorizado.setText("Buscar");
        btnBuscarAutorizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutorizadoActionPerformed(evt);
            }
        });

        lblNombres1.setText("Nombre");

        txtNombreAutorizado.setEditable(false);

        jLabel8.setText("Apellido 1");

        txtApellidoAutorizado.setEditable(false);

        jLabel5.setText("DNI del Autorizado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombres1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDniAutorizado, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtNombreAutorizado)
                    .addComponent(txtApellidoAutorizado))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAutorizado)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniAutorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAutorizado)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres1)
                    .addComponent(txtNombreAutorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtApellidoAutorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setText("ALUMNO");

        jLabel4.setText("AUTORIZADO");

        btnAddAutorizacion.setText("Añadir");
        btnAddAutorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAutorizacionActionPerformed(evt);
            }
        });

        btnRestablecer.setText("Restablecer");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(btnAddAutorizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestablecer)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAutorizacion)
                    .addComponent(btnRestablecer)
                    .addComponent(btnEliminar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        // TODO add your handling code here:
        buscarAlumno();
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnBuscarAutorizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorizadoActionPerformed
        // TODO add your handling code here:
        buscarAutorizado();
    }//GEN-LAST:event_btnBuscarAutorizadoActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        // TODO add your handling code here:
        restablecerCampos();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnAddAutorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAutorizacionActionPerformed
        // TODO add your handling code here:
        agregarAutorizacion();
    }//GEN-LAST:event_btnAddAutorizacionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarAutorizacion();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAutorizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAutorizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAutorizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAutorizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAutorizaciones().setVisible(true);
            }
        });
    }

    private void buscarAlumno() {
        String dni = txtDniAlumno.getText();
        AlumnoDaoImp alumnoDao = AlumnoDaoImp.getInstance();

        try {
            Alumno alumno = alumnoDao.getByDni(dni);
            miAlumnoInterno = alumno;
            if (alumno != null) {
                txtNombreAlumno.setText(alumno.getNombre());
                txtApellidoAlumno.setText(alumno.getApellido1());
                // Setear otros campos con la información necesaria del alumno
            } else {
                JOptionPane.showMessageDialog(this, "Alumno no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
                // Limpiar los campos de alumno
                txtNombreAlumno.setText("");
                txtApellidoAlumno.setText("");
                // Limpiar otros campos del alumno
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAutorizaciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al buscar el alumno", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarAutorizado() {
        String dni = txtDniAutorizado.getText();
        AutorizadoDaoImp autorizadoDao = AutorizadoDaoImp.getInstance();

        try {
            Autorizado autorizado = autorizadoDao.getByDni(dni);
            miAutorizadoInterno = autorizado;
            if (autorizado != null) {
                txtNombreAutorizado.setText(autorizado.getNombre());
                txtApellidoAutorizado.setText(autorizado.getApellido1());
                // Setear otros campos con la información necesaria del autorizado
            } else {
                JOptionPane.showMessageDialog(this, "Autorizado no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
                // Limpiar los campos del autorizado
                txtNombreAutorizado.setText("");
                txtApellidoAutorizado.setText("");
                // Limpiar otros campos del autorizado
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAutorizaciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al buscar el autorizado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void restablecerCampos() {
        txtDniAlumno.setText("");
        txtNombreAlumno.setText("");
        txtApellidoAlumno.setText("");
        txtDniAutorizado.setText("");
        txtNombreAutorizado.setText("");
        txtApellidoAutorizado.setText("");
    }

    private void agregarAutorizacion() {
        if (miAlumnoInterno == null || miAutorizadoInterno == null) {
            JOptionPane.showMessageDialog(this, "Por favor, busque un alumno y un autorizado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        AutorizacionesDaoImp autorizacionesDao = AutorizacionesDaoImp.getInstance();

        try {
            Autorizaciones autorizacion = new Autorizaciones(miAlumnoInterno.getId(), miAutorizadoInterno.getId());
            int rowsAffected = autorizacionesDao.add(autorizacion);

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Autorización agregada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                restablecerCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar la autorización", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar la autorización", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminarAutorizacion() {
        if (miAlumnoInterno == null || miAutorizadoInterno == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un alumno y un autorizado");
            return;
        }

        int idAlumno = miAlumnoInterno.getId();
        int idAutorizado = miAutorizadoInterno.getId();

        try {
            AutorizacionesDaoImp autorizacionesDao = AutorizacionesDaoImp.getInstance();
            Autorizaciones autorizacion = autorizacionesDao.getById(idAlumno, idAutorizado);

            if (autorizacion != null) {
                autorizacionesDao.delete(autorizacion);
                restablecerCampos();
                JOptionPane.showMessageDialog(this, "Autorización eliminada correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "No existe una autorización para el alumno y autorizado seleccionados");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAutorizaciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al eliminar la autorización", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAutorizacion;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnBuscarAutorizado;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombres1;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextField txtApellidoAutorizado;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtDniAutorizado;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreAutorizado;
    // End of variables declaration//GEN-END:variables
}
